version: "3"
services:
  server:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8484:8484
      - 8585-8989:8585-8989
    volumes:
      - ./data:/kinoko/data
      - ./wz:/kinoko/wz
    environment:
      # ServerConstants
      CENTRAL_HOST: "127.0.0.1"
      CENTRAL_PORT: "8282"
      SERVER_HOST: "127.0.0.1"
      DATABASE_HOST: "database"
      # ServerConfig
      WORLD_ID: "0"
      WORLD_NAME: "Kinoko"
      CHANNEL_COUNT: "1"
      AUTO_CREATE_ACCOUNT: "true"
      REQUIRE_SECONDARY_PASSWORD: "true"
      WZ_DIRECTORY: "/kinoko/wz"
      DATA_DIRECTORY: "/kinoko/data"
      COMMAND_PREFIX: "!"
      DEBUG_MODE: "true"
  database:
    image: cassandra:5.0.0-jammy
    ports:
      - 9042:9042
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 5
